### ISSUE TITLE
ortizmelissa Github progress tracker 

### ISSUE THREAD

**Issue by ortizmelissa** [githubteacher/jubilant-barnacle#16]
- [x] Create a branch based off of `master`
- [ ] Add some commits
- [ ] Open a PR
- [ ] Add additional commits (_optional_ - based on collaboration)
- [ ] **Merge** - only when you receive one or more :+1:
