### ISSUE TITLE
etienne-naugle progress tracking

### ISSUE THREAD

**Issue by etienne-naugle** [githubteacher/jubilant-barnacle#8]
Initial tasks
- [x] Create **branch** based off of `master`
- [x]  add some **commits**
- [x] create _pull request_
- [x] add additional commits
- [x] merge with master when we receive :+1:
